name: dangrlab
favicon: null
layout_spectrum: 0.87246
typography_spectrum: 0.47283
title: the koloring book
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 1
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
